### ISSUE TITLE
Many to many association

### ISSUE THREAD

**Issue by adrienpoly** [bessey/brillo#14]
Hey 

Thanks for this excellent gem
I am trying to back up a subset of my production db 
with one to many associations it works perfectly, but I am unable to get it to work for a many to many association.

```ruby
class UserClassroom < ApplicationRecord
  belongs_to :user
  belongs_to :classroom
end

class User < ApplicationRecord
  has_many :user_classrooms
  has_many :classrooms, throught: :user_classrooms
end

class Classromm < ApplicationRecord
  has_many :user_classrooms
  has_many :users, throught: :user_classrooms
end
````

This doesn't seem to work UserClassroom.count -> 0
```yml
explore:
  user: 
    tactic: oldest
    associations:
     - user_classrooms
     - users
```
my `users` and `classrooms` are in the db but I don't have the join table to make the link between them

Thanks
